### ISSUE TITLE
UI/UX feedback

### ISSUE THREAD

**Issue by gsong** [xiaozhong21/Investory#15]
- Searching for non-existen stock ticker crashes the app

  <https://investory-app.herokuapp.com/stocks/intl>

- Navigating to news items shows blank page

  <https://investory-app.herokuapp.com/stocks/i6zt4/c1.u/rcs1o3f/rxsWvi0wY/lHL9p/wNa:d12Gaeo/oka6jshnPCEp.5li76g2ntPscmMhtszPEe6wedE>

- Adding a non-existent stock ticker to backtest yeilds no results
- Editing portfolio would be better if it's populated with existing portfolio data.
- Light up the nav item for the section you're currently in.
- Why is "Bactest Portfolio" its own section? When the portfolio you create is in "My Stocks?"
- Go all in on "Inve$story" for the entire app. E.g. instead of "Investment $tory."

**Comment by xiaozhong21** [comment]
> * Searching for non-existen stock ticker crashes the app
>   https://investory-app.herokuapp.com/stocks/intl
> * Navigating to news items shows blank page
>   https://investory-app.herokuapp.com/stocks/i6zt4/c1.u/rcs1o3f/rxsWvi0wY/lHL9p/wNa:d12Gaeo/oka6jshnPCEp.5li76g2ntPscmMhtszPEe6wedE
> * Adding a non-existent stock ticker to backtest yeilds no results
> * Editing portfolio would be better if it's populated with existing portfolio data.
> * Light up the nav item for the section you're currently in.
> * Why is "Bactest Portfolio" its own section? When the portfolio you create is in "My Stocks?"
> * Go all in on "Inve$story" for the entire app. E.g. instead of "Investment $tory."

Thank you George for the feedback! I implemented some enhancements to address the problems:
- Added better error-handling features
- Currently using sandbox API so news won't redirect. Will switch API accounts for news to show up
- Renamed "Backtest Portfolio" to "Add Portfolio" so it's clear that it is a form. Because it's the main feature of the app, I want to make sure users have access to the form wherever they are in the app
- Unified branding by using "Inve$tory" whenever appropriate
